name: 👽 Atmos Pro Terraform Plan
run-name: plan ${{ inputs.component }}/${{ inputs.stack }}/${{ inputs.atmos_pro_run_id}}

on:
  workflow_dispatch:
    inputs:
      atmos_pro_run_id:
        description: "Atmos Pro Run ID"
        type: string
      sha:
        description: "Commit SHA"
        type: string
      component:
        description: "Component"
        required: true
        type: string
      stack:
        description: "Stack"
        required: true
        type: string
      upload:
        description: "Upload plan status to Atmos Pro"
        type: string # All args for Atmos Pro are strings
        required: false
        default: "false"

# Avoid running the same stack in parallel mode (from different workflows)
# This applied to across workflows to both plan and apply
concurrency:
  group: "${{ inputs.stack }}-${{ inputs.component }}"
  # Cancel stale plans so the most recent commit's plan always runs
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT (OIDC) token
  contents: read # This is required for actions/checkout
  checks: write # This is required for Atmos set gha statuses
  statuses: write # This is required to post status checks back to the PR commit

jobs:
  atmos-plan:
    name: ${{ inputs.component }}-${{ inputs.stack }}

    runs-on:
      - "ubuntu-latest"

    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha }}

      - name: Plan Atmos Component
        shell: bash
        env:
          # Workspace ID is required for uploading the plan status to Atmos Pro.
          ATMOS_PRO_WORKSPACE_ID: ${{ vars.ATMOS_PRO_WORKSPACE_ID }}
          ATMOS_PRO_BASE_URL: ${{ vars.ATMOS_PRO_BASE_URL }}          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ATMOS_PROFILE: github
          GITHUB_SHA: ${{ inputs.sha }}
          COMPONENT: ${{ inputs.component }}
          STACK: ${{ inputs.stack }}
        run: |
          atmos terraform plan "${COMPONENT}" -s "${STACK}" --upload-status
